# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    Contents: '**/*'
    TargetFolder: '$(build.artifactstagingdirectory)'



- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(build.artifactstagingdirectory)'
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN (1072aca0-d739-4dd8-80c6-773927102910)'
    Destination: 'AzureVMs'
    storage: 'cicdstoragearyakumar'
    resourceGroup: 'SERVER2022_GROUP'
    vmsAdminUserName: 'aryak'
    vmsAdminPassword: 'It is warArya$'
    TargetPath: '$env:windir\DevOpsBasic'